Neos:
  Neos:
    userInterface:
      defaultLanguage: 'de'
      #backendLoginForm:
        #backgroundImage: 'resource://Js.Bookworm/Public/Images/login_.jpg'
    Ui:
      resources:
        javascript:
          'Js.Bookworm:CustomStylingForCkEditor':
            resource: resource://Js.Bookworm/Public/CustomStylingForCkEditor/Plugin.js

MOC:
  ImageOptimizer:
    useGlobalBinary: true
    #globalBinaryPath: ''
