#
# Resizimg f√ºr Bilder
#

Neos:
  Neos:
    userInterface:
      inspector:
        dataTypes:
          Neos\Media\Domain\Model\ImageInterface:
            editorOptions:
              features:
                resize: true
