Neos:
  Neos:
    eventLog:
      enabled: TRUE
    userInterface:
      defaultLanguage: 'de'
      #backendLoginForm:
        #backgroundImage: 'resource://Js.Bookworm/Public/Images/login_.jpg'
MOC:
  ImageOptimizer:
    useGlobalBinary: true
    #globalBinaryPath: ''
